version: 0.2

phases:
  install:
    runtime-version:
      python: 3.11

  pre_build:
    commands:
      - echo "Building website"

  build:
    commands:
      - echo "Post-building website"
      - aws s3 sync build/ s3://test-iccc-bucket/ --region eu-central-1 --delete
    finally:
      - echo "Build done successfully"
